### ISSUE TITLE
International Debt reform does not reward indicated civilization progress

### ISSUE THREAD

**Issue by rogerburks** [moretrim/PFH#24]
For uncivs, the reform International Debt `finance_reform_two` indicates that it awards 35% civilization progress, but actually awards only 25%.

In issues.txt it properly contains:  `civilization_progress_modifier = 0.35`

Possibly 25% is the maximum? More testing is needed. As a last resort, this could be modified to 25% if this is truly all that it can reward.

**Comment by moretrim** [comment]
If you change the progress modifier to e.g. `0.34`, then by the time you pick the last financial reform you are at 34% progress. My thinking is that the game was never designed with Westernisation reforms that use `next_step_only = yes` (this is an HPM/HFM thing), so it keeps track of the right numbers but displays the wrong tooltip. (We know that's a game bug because other numbers displayed on the tooltip certainly are per-step, not total.)

Up next is the question as to whether the mod designers were aware of this limitation when they set e.g. `finance_reform_two` to `0.35`. To be frank I am not able to tell. The progress-per-point efficiency of the different reform lines vary a lot, but so do their effects. All in all this matter is best left for upstream.
