### ISSUE TITLE
Heavenly Kingdom is not Mahayana

### ISSUE THREAD

**Issue by rogerburks** [moretrim/PFH#40]
The Middle Kingdom event (90900) in China.txt westernizes Heavenly Kingdom in the same way that the Qing Empire would be westernized, including changing the nation's religion to Mahayana for no apparent reason. I have created separate paths for Heavenly Kingdom and Qing Empire westernization, however there could be lingering problems that may need to be addressed.

**Comment by moretrim** [comment]
A quick overview of the situation. The Westernisation events are set by:

https://github.com/moretrim/PFH/blob/bc42da48dbfbc09d2257055a9c8a839b33a111e7/PFH/common/on_actions.txt#L126-L131

These are:

- [`90910`](https://github.com/moretrim/PFH/blob/699f8f240acf584dad64c2e6a9316ade0f649563/PFH/events/CivilizationAndGunBoats.txt#L4415) in general
- [`90900`](https://github.com/moretrim/PFH/blob/699f8f240acf584dad64c2e6a9316ade0f649563/PFH/events/China.txt#L6) for the big Chinas (`QNG`, `CHI`, or `TPG`)
- [`90903`](https://github.com/moretrim/PFH/blob/699f8f240acf584dad64c2e6a9316ade0f649563/PFH/events/China.txt#L238) for the Chinese minors/substates (if they beat the big Chinas to the punch)

Out of all of these, only `90900` changes state religion. This only takes place in HFM, [upstream does not affect religion](https://github.com/arkhometha/Historical-Project-Mod/blob/c0fcdf2f0f89e3bd7c49a082f4e6f980ace5251f/HPM/events/China.txt#L6).

Given the circumstances, I'm inclined to just chuck the religion switch away—if there's a good reason HFM has it, it simply doesn't say. We can revert the change if it turns out it's somehow harmful.

**Comment by rogerburks** [comment]
This makes sense to me, and is easier than my splitting things up. This is the passage where things go a bit awry, which seems to be associated possibly with the `missionary_activity` flag. I really do not know exactly what those flags do without looking them up, and so I'll want to do that before calling this one finished.

https://github.com/moretrim/PFH/blob/699f8f240acf584dad64c2e6a9316ade0f649563/PFH/events/China.txt#L30-L35

**Comment by rogerburks** [comment]
For `protestant_country` , this seems to be one of several flags that govern colony organization, and so I think it is highly advisable to keep it for Heavenly Kingdom. For instance:

- [`organize_togo`](https://github.com/moretrim/PFH/blob/bc42da48dbfbc09d2257055a9c8a839b33a111e7/PFH/decisions/New%20Colonies.txt#L347-L350)

https://github.com/moretrim/PFH/blob/bc42da48dbfbc09d2257055a9c8a839b33a111e7/PFH/decisions/New%20Colonies.txt#L347-L350

`change_to_protestant` seems to only affect a flag that is given to an unciv in the "$FROMCOUNTRY_ADJ$ Missionaries" event, again best to be retained but mostly harmless for Heavenly Kingdom:

- [`90962`](https://github.com/moretrim/PFH/blob/bc42da48dbfbc09d2257055a9c8a839b33a111e7/PFH/events/CivilizationAndGunBoats.txt#L5138-L5146)

https://github.com/moretrim/PFH/blob/bc42da48dbfbc09d2257055a9c8a839b33a111e7/PFH/events/CivilizationAndGunBoats.txt#L5138-L5146

`missionary_activity` looks like something that should be cleared upon any westernization, and is a modifier affecting various things, including militancy, conversion chance, and research points.

**Comment by rogerburks** [comment]
Here I remembered that I said I was going to update this and forgot to do it. I am uploading an update now, and will playtest it to see if the removal of religion specification upon westernization does anything.

**Comment by rogerburks** [comment]
To summarize with the new fixes, you can tell what the state religion is (as long as there are no other effects that convert pops), because other pops will have a conversion factor. Here immediately before westernization, Heavenly Kingdom is protestant:

![image](https://user-images.githubusercontent.com/17787203/69500522-d479b380-0eb0-11ea-9e96-905db6221d61.png)

After westernization, the conversion is still working:

![image](https://user-images.githubusercontent.com/17787203/69500548-0ab73300-0eb1-11ea-91b4-41b32f8f4d08.png)

**Comment by rogerburks** [comment]
For the Qing Empire given these changes, before westernization, pops are converted to Mahayana:

![image](https://user-images.githubusercontent.com/17787203/69500616-7b5e4f80-0eb1-11ea-83b9-f3ef6379cb1c.png)

After westernization this is still true:

![image](https://user-images.githubusercontent.com/17787203/69500644-b2346580-0eb1-11ea-8fd6-716e71255d27.png)

Therefore, the changes seem to have no ill effect.
